### ISSUE TITLE
Onnx conversion

### ISSUE THREAD

**Issue by Source82** [olonok69/LLM_Notebooks#1]
Thanks for the code please can you provide the script you used to convert florence 2 to onnx

**Comment by olonok69** [comment]
This still work in progress. There is scripts to convert to OpenVino format. depending what you want to do It is good enought. I have the Florence2 runing in CPU converted to OpenVino format

**Comment by olonok69** [comment]
If you are interested on that Process look at this video in my Youtube channel https://youtu.be/EIUIldcpq0I

the code it is also available on this repo
