### ISSUE TITLE
Onnx for Florence-2

### ISSUE THREAD

**Issue by Source82** [olonok69/LLM_Notebooks#2]
Hi,

Great repo you have here. 

Please can you show us how you convert florence-2 to onnx, for example for single use task like <OD> or <CAPTION>.

Thanks

**Comment by olonok69** [comment]
Hi you can look at this video https://youtu.be/D9mOMT35sRU 
This guys https://github.com/curiosity-ai/florence2-sharp/tree/main hove already done in Csharp , you can download the component in onnx format using what I explain in the video
regards

**Comment by olonok69** [comment]
by the way , I don't attend issues in this repo. This repo it is only to support the work I am doing on the YouTube channel as I explain in the readme. Please look for what you need there and any video have a connection to the code in this repo
videos are in English and Spanish
regards
